### ISSUE TITLE
why do you use Redis Pubsub 

### ISSUE THREAD

**Issue by MaryLilian** [adaptive-architecture/common-utilities#8]
Hi, I am reading your project and I love this project
I have a question, why do you choose Redis Pubsub in your project instead of others like RabbitMQ or Kafka, are there any special features that others dont have it. Can you share me it. I am wondering when I should choose Redis Pubsub instead of others like RabbitMQ or Kafka

**Comment by validide** [comment]
There's nothing special about Redis. It just happens that when I wrote this I was working on a project that already used Redis for other functionalities.

I just needed a simple way of making the wire-up easy and reduce the amount of boilerplate code needed.

RabbitMQ and Kafka might be better from multiple perspectives (like resilience) perspective but I did not want to add an extra dependency to the project.

You could implement a `RabbitMQMessageHub` or a `RabbitMQMessageHub` yourself.
